Add beans for grpc server and client metrics interceptors
micronaut-projects/micronaut-micrometer pull request #321
Opened 2021-11-20 05:58 UTC by jameskleeh

2021-11-21 11:35 UTC, graemerocher commented
I'm wondering, wouldn't it be better to reverse this, ie. have a compileOnly dependency on micrometer in the gRPC module?

2021-11-22 15:20 UTC, jameskleeh commented
@graemerocher I think it would be easier to ensure compatibility with the code being here. The only thing this relies on from gRPC is a couple of interfaces so the likelihood of incompatibility with a new version of gRPC is lower imo.

2021-11-22 17:30 UTC, graemerocher requested changes

2021-11-22 17:30 UTC, graemerocher commented on micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/grpc/GrpcMetricsListenerFactory.java
> +class GrpcMetricsListenerFactory {
if it is package private probably annotate it with `@Internal`

2021-11-22 19:37 UTC, merged