Fix #458 (Issue with websockets)
micronaut-projects/micronaut-micrometer pull request #511
Opened 2023-03-09 13:51 UTC by n0tl3ss

This PR properly resolves uri template from request object. It solves problem with websocket parametrised uri request.

2023-03-09 13:55 UTC, graemerocher requested changes

2023-03-09 13:55 UTC, graemerocher commented on micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java
> +        Optional<Object> routeInfo = request.getAttribute(HttpAttributes.ROUTE_INFO)
change this to `request.getAttribute(HttpAttributes.ROUTE_INFO, UriRouteMatch.class)` and you can avoid the filter and the cast and change the return type to `Optional<String>`

2023-03-10 11:32 UTC, merged

2024-10-09 11:38 UTC, frank-mueller-at-kiwigrid-com commented
I'm new to Github, so please apologize if this is not the correct way to re-open a bug.
Please advise if I should do it in a different way.

After upgrading my Micronaut project to Micronaut Micrometer 5.8.0 the built-in metrics "http_client_requests_seconds_count" & "http_client_requests_seconds_sum" metrics seem to be broken.

**Environment**

- Micronaut BOM 
io.micronaut.platform:micronaut-platform:4.6.2
which resolves to
io.micronaut.micrometer:micronaut-micrometer-registry-prometheus:5.8.0
io.micrometer:micrometer-core:1.13.3
io.prometheus:simpleclient:0.16.0

- Micronaut app with 2 HTTP clients configured
Client A neither sets "micronaut.http.route.template" nor "micronaut.http.serviceId" to the request
Client B sets "micronaut.http.route.template" and "micronaut.http.serviceId" to the request

- Micronaut app configured to write web metrics using Prometheus

**Steps to reproduce**
- run your Micronaut App
- initiate an action that let Client A send a request and thus 
- initiate an action that let Client B send a request
- check the "http_client_requests_seconds_count" & "http_client_requests_seconds_sum" metrics at the "/prometheus" endpoint of your Micronaut App

**Expected**
You find metrics produced by both client.

**Actual**
You find metrics produced by Client A only. Or more general, you find metrics of those client that writes as the first to the metric. The same would happen if Client B goes first.

**Assumption**
With this bugfix, ClientRequestMetricRegistryFilter & WebMetricsPublisher only writes the "uri" and/or "serviceId" tag if the corresponding request attribute was set by the client.
In the given example, this behavior causes two write operations happen to the same metric with a different set of tags.
However the Prometheus client does not like that. 
See https://github.com/micrometer-metrics/micrometer/issues/877 and https://github.com/prometheus/client_java/issues/696

As I'm just a user of the built-in "http_client_requests_seconds_count" & "http_client_requests_seconds_sum" metrics I have no chance to change that behavior.

**Suggested fix**
As there seems to be different opinions about whether this is a problem in Prometheus client or in Micrometer Prometheus integration and since it unclear when the actual problem gets fixed, I suggest to fix it in Micrometer core:

Let ClientRequestMetricRegistryFilter & WebMetricsPublisher always write the "uri" and "serviceId" tag. If "micronaut.http.route.template" or "micronaut.http.serviceId" are missing at the request, use an artifical constants as tag value.

2024-10-29 04:28 UTC, sdelamo commented
@frank-mueller-at-kiwigrid-com [create a separate issue](https://github.com/micronaut-projects/micronaut-micrometer/issues) if you think it is necessary