Micrometer obsevation integration
micronaut-projects/micronaut-micrometer pull request #585
Opened 2023-07-10 14:35 UTC by n0tl3ss

- This PR instruments: https://micrometer.io/docs/observation for metrics and traces.

2023-07-11 13:47 UTC, dstepanov requested changes

2023-07-11 13:47 UTC, dstepanov commented on micrometer-observation/src/main/java/io/micronaut/micrometer/observation/DefaultObservedFactory.java
> +        @Nullable List<ObservationPredicate> observationPredicates,
I don't think we need nullable

2023-07-11 13:47 UTC, dstepanov commented on micrometer-observation/src/main/java/io/micronaut/micrometer/observation/http/server/ObservationServerFilter.java
> +                    .contextWrite(ctx -> ReactorPropagation.addPropagatedContext(ctx, propagatedContext));
`ReactorPropagation.addPropagatedContext` is not needed anymore

2023-07-12 11:20 UTC, marcingrzejszczak requested changes
Added a remark related to groupings of handlers, other than that LGTM! Great job!

2023-07-12 11:20 UTC, marcingrzejszczak commented on micrometer-observation/src/main/java/io/micronaut/micrometer/observation/DefaultObservedFactory.java
> +        observationHandlers.forEach(observationRegistry.observationConfig()::observationHandler);
I don't think this is enough. You should group all `TracingObservationHandlers` together with a `FirstMatchingCompositeHandler`. Same for `MeterObservationHandler`. Check this out https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/observation/ObservationAutoConfiguration.java#L85-L107

2023-07-12 11:20 UTC, marcingrzejszczak commented on micrometer-observation/src/main/java/io/micronaut/micrometer/observation/DefaultObservedFactory.java
> +    public ObservationHandler<?> defaultTracingObservationHandler(Tracer tracer) {
This has to be last in the `TracingObservationHandler` list AFTER `sender` and `receiver`

2023-07-12 15:44 UTC, dstepanov commented
I would extract the HTTP stuff into a particular module.

2023-07-12 17:08 UTC, dstepanov approved these changes

2023-07-13 10:56 UTC, graemerocher commented
this should bump the version to 5.1 snapshot

2023-07-13 12:19 UTC, marcingrzejszczak approved these changes

2023-07-17 20:57 UTC, graemerocher approved these changes

2023-07-18 06:16 UTC, merged

2023-07-18 08:06 UTC, marcingrzejszczak commented
:partying_face: congrats to everyone :)

2023-07-18 16:29 UTC, jonatan-ivanov commented
Thanks for adding this!
Should this issue be closed? https://github.com/micronaut-projects/micronaut-micrometer/issues/492