Adding support for histograms
micronaut-projects/micronaut-micrometer pull request #740
Opened 2024-04-17 16:55 UTC by lcavadas

- Added a new HttpHistogramMeterFilterFactory class to contribute to the configuration of the 'http.server.requests' and 'http.client.requests' meters.

- Renamed the existing HttpMeterFilterFactory to HttpPercentilesMeterFilterFactory in order for the naming of both classes to be consistent.

- Added test to validate configuration takes effect.

2024-04-17 16:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-micrometer?pullRequest=740) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-micrometer?pullRequest=740) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-micrometer?pullRequest=740) it.</sub>

2024-04-19 05:45 UTC, sdelamo requested changes

2024-04-19 05:45 UTC, sdelamo commented on micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/HttpPercentilesMeterFilterFactory.java
> +public class HttpPercentilesMeterFilterFactory {
This is a breaking change. We cannot rename public classes in a patch version.

2024-04-19 07:29 UTC, lcavadas commented on micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/HttpPercentilesMeterFilterFactory.java
> +public class HttpPercentilesMeterFilterFactory {
Done, classname back to original 👍

2024-05-22 09:44 UTC, graemerocher approved these changes

2024-05-22 09:50 UTC, merged

2024-05-22 09:50 UTC, graemerocher commented
Thanks for the contribution!

2024-06-13 12:27 UTC, scprek reviewed
Have the docs been updated? This is the default in spring I think and has caught many of our teams off guard so we had a similar change.